//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public byte Id { get; set; }
        //reguired kýsýtlama demektir. personel kýsmý boþ geçilemez. eðer boþ geçilirse personel adý boþ geçilemez hatasý vericek. DataAnnotations

        [Reguired(ErrorMessage="Personel Adý Boþ Geçilemez")]
        public  string  Employees { get; set; }
    }
}
